name: Release

on:
  push:
    tags:
      - 'v*'  # триггер на git tag вида v0.1.0, v0.0.1-test и т.п.

permissions:
  contents: write   # для создания GitHub Release
  packages: write   # для пуша Docker-образов в GHCR

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🧰 Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: 🔨 Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: test/Dockerfile.hello
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/cloudeck:${{ github.ref_name }}


      - name: 📦 Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
